ALTER TABLE public.posts ADD if not exists uuid_user uuid null;
ALTER TABLE public.posts ADD if not exists likes int8 not null default 0;
ALTER TABLE public.posts ADD if not exists loved int8 not null default 0;
ALTER TABLE public.posts ADD if not exists wows int8 not null default 0;
ALTER TABLE public.posts ADD if not exists interesting int8 not null default 0;
ALTER TABLE public.posts ADD if not exists dislikes int8 not null default 0;
ALTER TABLE public.posts ADD if not exists reacts int8 not null default 0;
ALTER TABLE public.posts ADD if not exists pinned boolean not null default false;
ALTER TABLE public.posts ADD if not exists type varchar not null default 'public';
ALTER TABLE public.posts ADD if not exists classroom uuid null;