ALTER TABLE service_default_product ADD COLUMN IF NOT EXISTS price NUMERIC(15, 2) NULL;
ALTER TABLE sale_service_product ADD COLUMN IF NOT EXISTS price NUMERIC(15, 2) NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS size_per_unit INTEGER NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS remain_unit INTEGER NULL;
