ALTER TABLE sale ADD COLUMN IF NOT EXISTS subtotal_services NUMERIC(15, 2) NULL;
ALTER TABLE sale ADD COLUMN IF NOT EXISTS commissions NUMERIC(15, 2) NULL;
ALTER TABLE sale ADD COLUMN IF NOT EXISTS commission_discount NUMERIC(15, 2) NULL;
ALTER TABLE sale ADD COLUMN IF NOT EXISTS subtotal_service_products NUMERIC(15, 2) NULL;
ALTER TABLE sale ADD COLUMN IF NOT EXISTS subtotal_products NUMERIC(15, 2) NULL;
ALTER TABLE sale ADD COLUMN IF NOT EXISTS discount_percent NUMERIC(15, 2) NULL;
ALTER TABLE sale ADD COLUMN IF NOT EXISTS subtotal_discount NUMERIC(15, 2) NULL;