ALTER TABLE sale ADD COLUMN IF NOT EXISTS has_iva BOOLEAN NULL;
ALTER TABLE sale ADD COLUMN IF NOT EXISTS iva_service BOOLEAN NULL;
ALTER TABLE sale ADD COLUMN IF NOT EXISTS iva_product BOOLEAN NULL;
ALTER TABLE sale ADD COLUMN IF NOT EXISTS iva INTEGER NULL;